image: node:20-alpine

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

variables:
  PNPM_HOME: .pnpm-store
  DEPENDABOT_IMAGE: docker.io/andrcuns/dependabot-gitlab:latest

test_async:
  script:
    - corepack enable
    - pnpm install
    - pnpm test
    - pnpm lint

.dependabot-gitlab:
  image:
    name: $DEPENDABOT_IMAGE
    entrypoint: ['']
  variables:
    GIT_STRATEGY: none
    PACKAGE_MANAGER: $CI_JOB_NAME
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN
    SETTINGS__GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
    SETTINGS__STANDALONE_CACHE_PATH: $CI_PROJECT_DIR/.dependabot/cache
  script:
    - cd /home/dependabot/app
    - ./scripts/run.sh --project-name "$CI_PROJECT_PATH" --package-ecosystem "$PACKAGE_MANAGER" --directory "${DIRECTORY:-/}"
  cache:
    - key: dependabot
      policy: pull-push
      paths:
        - $CI_PROJECT_DIR/.dependabot/cache

npm:
  extends: .dependabot-gitlab
  rules:
    - if: $DEPENDENCY_UPDATES_DISABLED
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /schedule|api|web/ && $PACKAGE_MANAGER_SET =~ /(\bnpm|pnpm\b)/'
