# Configuration taken from this article:
# https://paperless.blog/dependabot-on-gitlab
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'realm'
      - dependency-name: 'react'
      - dependency-name: 'react-native'
      - dependency-name: 'react-native-push-notifications'
