require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'drip' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'dripTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!

  # This is fix to make ios build see images, should be removed after upgrade to rn 0.63.2
  # https://stackoverflow.com/questions/63949851/react-native-ios-not-showing-images-pods-issue
  # post_install do |installer|
  #   # flipper_post_install(installer)
  #   find_and_replace("../node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m",
  #   "_currentFrame.CGImage;","_currentFrame.CGImage ;} else { [super displayLayer:layer];")
  #   find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  #   "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
  #   find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
  #   "RCTBridgeModuleNameForClass(strongModule))", "RCTBridgeModuleNameForClass(Class(strongModule)))")
  # end

  def find_and_replace(dir, findstr, replacestr)
    Dir[dir].each do |name|
        text = File.read(name)
        replace = text.gsub(findstr,replacestr)
        if text != replace
            puts "Fix: " + name
            File.open(name, "w") { |file| file.puts replace }
            STDOUT.flush
        end
    end
    Dir[dir + '*/'].each(&method(:find_and_replace))
  end
end
